Go back to sudo enabled Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,57 +1,68 @@
-# This Travis job script has been generated by a script via
-#
-#   make_travis_yml_2.hs 'haskell-gi.cabal'
-#
-# For more information, see https://github.com/hvr/multi-ghc-travis
-#
-language: c
-sudo: false
+sudo: required
+dist: trusty
 
-git:
-  submodules: false  # whether to recursively clone submodules
-
-cache:
-  directories:
-    - $HOME/.cabal/packages
-    - $HOME/.cabal/store
-
-before_cache:
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  # remove files that are regenerated by 'cabal update'
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+env:
+ - CABALVER=1.18 GHCVER=7.8.3
+ - CABALVER=1.18 GHCVER=7.8.4
+ - CABALVER=1.22 GHCVER=7.10.1
+ - CABALVER=1.22 GHCVER=7.10.2
+ - CABALVER=1.22 GHCVER=7.10.3
+ - CABALVER=1.24 GHCVER=8.0.1
+ - CABALVER=head GHCVER=head
 
 matrix:
-  include:
-    - compiler: "ghc-7.8.4"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.8.4,libgirepository1.0-dev], sources: [hvr-ghc]}}
-    - compiler: "ghc-7.10.3"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.10.3,libgirepository1.0-dev], sources: [hvr-ghc]}}
-    - compiler: "ghc-8.0.1"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.1,libgirepository1.0-dev], sources: [hvr-ghc]}}
+  allow_failures:
+    - env: CABALVER=head GHCVER=head
 
 before_install:
- - HC=${CC}
- - unset CC
- - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
- - PKGNAME='haskell-gi'
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
+ - travis_retry sudo apt-get install -y libgirepository1.0-dev libwebkitgtk-3.0-dev libwebkit2gtk-3.0-dev libpoppler-glib-dev libvte-2.90-dev libgtksourceview-3.0-dev libgstreamer1.0-dev
+ - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
 
 install:
  - cabal --version
- - travis_retry cabal update -v
- - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install Cabal cabal-install
+ - hash -r
+ - cabal --version
 
-# Here starts the actual work to be performed for the package under test;
-# any command which exits with a non-zero exit code causes the build to fail.
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
- - cabal new-build
-# The version of gtk etc. in Ubuntu Precise is ancient, so do not build the bindings until we can update to Trusty.
-# - pushd bindings
-# - ./newBuildTravis.sh
-# - popd
-# - cabal new-build testGtk
+ - pushd base
+ - cabal install --dependencies-only
+ - cabal configure
+ - cabal build
+ - cabal install
+ - popd
+ - cabal install --dependencies-only
+ - cabal configure
+ - cabal build
+ - cabal clean
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
-# EOF
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
+
+ - cd bindings
+ - |
+   if [ ${GHCVER%.*} = "7.8" ]; then
+     echo Warning: No packages checked since genBuildInfo.hs does not work on GHC 7.8
+   else
+     cabal install aeson aeson-pretty
+     for a in `./PKGS.sh`; do ./genBuildInfo.hs $a; done
+     cabal install -j3 ./GLib ./cairo ./Pango ./Gdk ./Gio ./GObject ./GdkPixbuf ./Atk
+     cabal install -j1 ./Gtk
+     cabal install -j3 ./GtkSource ./WebKit
+   fi
+notifications:
+  irc:
+    channels: "irc.freenode.net#gtk2hs"
+    skip_join: true
+email: true
